name: Pipeline
on: [push, pull_request]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Copia os arquivos do repo
        uses: actions/checkout@v3

      - name: Instalar o python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'

      - name: Instalar Poetry
        run: pip install poetry

      - name: Instalar dependÃªncias do projeto
        run: poetry install

      - name: Rodar os testes
        run: poetry run task test --cov-report=xml

      - name: Subir cobertura para o codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - uses: superfly/flyctl-actions/setup-flyctl@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Build and push Docker image to Fly.io
        run: |
          flyctl deploy --local-only
          flyctl deploy
